name: CI

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        node-version: 10.x
        persist-credentials: false
    - name: Install dependencies
      run: npm install
    - name: Generate page
      run: npm run generate
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: dist
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
