name: CI

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        node-version: 10.x
        persist-credentials: false
    - name: Install dependencies
      run: npm install
    - name: Generate page
      run: npm run generate
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        GITHUB_REF: refs/heads/development
        GH_PAT: ${{secrets.GH_PAT}}
        BUILD_DIR: ./dist
